In [79]:
import torch
import numpy as np
from torch import nn

In [142]:
score = [[[-0.1, -0.4, -0.5, -0.6], [-0.4, -0.8, -0.4, -0.3], [-0.9, -0.5, -0.2, -0.7]],
                 [[-0.6, -0.3, -0.8, -0.9], [-0.9, -0.5, -0.7, -0.4], [-0.7, -0.8, -0.2, -0.8]]]
top_score = [[-0.1, -0.2, -0.3], [-0.2, -0.3, -0.4]]
top_beamid = [[0, 2, 1], [2, 0, 1]]
top_wordid = [[0, 2, 3], [2, 1, 3]]

In [143]:
score= torch.FloatTensor(score)


In [144]:
batch_size, beam_size, vocab_size = score.shape
batch_size, beam_size, vocab_size

(2, 3, 4)

In [163]:
batch_size, beam_size, vocab_size = score.shape
top_score = torch.empty(batch_size,beam_size)
top_beamid = torch.empty(batch_size,beam_size)
top_wordid = torch.empty(batch_size,beam_size)
for batch in range(batch_size):
    score_batch = score[batch].view(-1)
    topKscores, unparsed_indices = torch.topk(score_batch, beam_size)
    word_indices = unparsed_indices % vocab_size
    beam_indices = unparsed_indices // vocab_size
    top_score[batch] = topKscores
    top_beamid[batch] = beam_indices
    top_wordid[batch] = word_indices
    # print(top_score)
    # print(topKscores, word_indices, beam_indices)
    

In [164]:
top_score, top_beamid, top_wordid

(tensor([[-0.1000, -0.2000, -0.3000],
         [-0.2000, -0.3000, -0.4000]]),
 tensor([[0., 2., 1.],
         [2., 0., 1.]]),
 tensor([[0., 2., 3.],
         [2., 1., 3.]]))

In [ ]:
sequences = torch.LongTensor(batch_size, beam_size, decode_max_length)

In [141]:
score = score.view(2, -1)
values, indices = torch.topk(score[0], 3)
values, indices

(tensor([-0.1000, -0.2000, -0.3000]), tensor([ 0, 10,  7]))

In [119]:
top_scores = torch.FloatTensor(batch_size, beam_size)
top_beamids = torch.LongTensor(batch_size, beam_size)
top_scores = torch.LongTensor(batch_size, beam_size)

In [127]:
k = torch.max(score[0][0]).item()

In [134]:
k

NameError: name 'long' is not defined

In [128]:
top_scores[0][0] = 

In [129]:
top_scores

tensor([[0, 0, 0],
        [0, 0, 0]])

In [122]:
for batch in range(batch_size):
    for beam in range(beam_size):
        print(torch.max(score[batch][beam]).item())

        top_scores[batch][beam] = 

-0.10000000149011612
-0.30000001192092896
-0.20000000298023224
-0.30000001192092896
-0.4000000059604645
-0.20000000298023224


In [121]:
top_scores

tensor([[0, 0, 0],
        [0, 0, 0]])

In [109]:
k.item()

-0.10000000149011612

In [105]:
top_scores[0][0] = k.values
top_scores[0][0] 

TypeError: can't assign a builtin_function_or_method to a torch.LongTensor

In [99]:
top_scores[0][0]

tensor(0)

In [6]:
top_K_beams, top_beamid = torch.sort(top_canditate, dim = 1, descending=True)
top_K_beams, top_beamid 

(tensor([[-0.1000, -0.2000, -0.3000],
         [-0.2000, -0.3000, -0.4000]]),
 tensor([[0, 2, 1],
         [2, 0, 1]]))

In [7]:
def topK(score):
    """
    For every example in a batch, we have generated K candidates (partial sequences) in beam search (K=beam_size).
    For each candidate, we will search for the next token from a vocabulary of V tokens (V=vocab_size). 
    So, we expand the old candidates to get (K * V) new candidates in total, and then we will prune the new
    candidates to only keep the top K candidates in the beam.
    Args: 
        score: torch.FloatTensor, [batch_size, beam_size, vocab_size]. 
               This tensor has the cummulated score of selecting the next token from a vocabuary
               for each old candidate for each example from a batch.
    Return:
        top_score: torch.FloatTensor, [batch_size, beam_size], the scores of the top K new candidates in the beam after pruning 
        top_beamid: torch.LongTensor, [batch_size, beam_size], the beam ids of the top K new candidates
        top_wordid: torch.LongTensor, [batch_size, beam_size], the word ids of the next tokens to construct the top K new candidates
    
    Example:
        Assuming batch_size = 2, beam_size = 3, vocab_size = 4, we have the inputs and outputs as follows:
        score = [[[-0.1, -0.4, -0.5, -0.6], [-0.4, -0.8, -0.4, -0.3], [-0.9, -0.5, -0.2, -0.7]],
                 [[-0.6, -0.3, -0.8, -0.9], [-0.9, -0.5, -0.7, -0.4], [-0.7, -0.8, -0.2, -0.8]]]
        top_score = [[-0.1, -0.2, -0.3], [-0.2, -0.3, -0.4]]
        top_beamid = [[0, 2, 1], [2, 0, 1]]
        top_wordid = [[0, 2, 3], [2, 1, 3]]  

    """
    top_score, top_wordid = score.max(dim = 2)
    top_score, top_beamid = torch.sort(top_score, dim = 1, descending=True)
    top_wordid = torch.gather(top_wordid, dim=1, index=top_beamid)
    return top_score, top_beamid, top_wordid

In [8]:
top_score, top_beamid, top_wordid = topK(score)
top_score, top_beamid, top_wordid

(tensor([[-0.1000, -0.2000, -0.3000],
         [-0.2000, -0.3000, -0.4000]]),
 tensor([[0, 2, 1],
         [2, 0, 1]]),
 tensor([[0, 2, 3],
         [2, 1, 3]]))

In [9]:
sorted, indices = torch.sort(score, dim = 2, descending=True)
sorted, indices

(tensor([[[-0.1000, -0.4000, -0.5000, -0.6000],
          [-0.3000, -0.4000, -0.4000, -0.8000],
          [-0.2000, -0.5000, -0.7000, -0.9000]],
 
         [[-0.3000, -0.6000, -0.8000, -0.9000],
          [-0.4000, -0.5000, -0.7000, -0.9000],
          [-0.2000, -0.7000, -0.8000, -0.8000]]]),
 tensor([[[0, 1, 2, 3],
          [3, 0, 2, 1],
          [2, 1, 3, 0]],
 
         [[1, 0, 2, 3],
          [3, 1, 2, 0],
          [2, 0, 1, 3]]]))

In [10]:
sorted_1, indices_1 = torch.sort(sorted, dim = 2, descending=True)
sorted, indices

(tensor([[[-0.1000, -0.4000, -0.5000, -0.6000],
          [-0.3000, -0.4000, -0.4000, -0.8000],
          [-0.2000, -0.5000, -0.7000, -0.9000]],
 
         [[-0.3000, -0.6000, -0.8000, -0.9000],
          [-0.4000, -0.5000, -0.7000, -0.9000],
          [-0.2000, -0.7000, -0.8000, -0.8000]]]),
 tensor([[[0, 1, 2, 3],
          [3, 0, 2, 1],
          [2, 1, 3, 0]],
 
         [[1, 0, 2, 3],
          [3, 1, 2, 0],
          [2, 0, 1, 3]]]))

In [11]:
t_sorted = sorted[:, : , 0]
t_indices = indices[:, : , 0]


In [12]:
t_sorted, t_indices = torch

TypeError: cannot unpack non-iterable module object

In [13]:
sortedScores = torch.sort(score.max(dim = 2).values, dim=2, descending = True)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [14]:
sortedScores


NameError: name 'sortedScores' is not defined

In [15]:
hiddens = torch.FloatTensor([[[0.6566, 0.2719, 0.7182, 0.1083],
                                    [0.1627, 0.4812, 0.1167, 0.4318],
                                    [0.1817, 0.2578, 0.5769, 0.2610]],

                                    [[0.9372, 0.4993, 0.5471, 0.9169],
                                    [0.8798, 0.6168, 0.6097, 0.8790],
                                    [0.6642, 0.4301, 0.5542, 0.3670]]])
beam_id = torch.LongTensor([[[1,1,1,1], [1,1,1,1], [0,0,0,0]], [[2,2,2,2], [0,0,0,0],[0,0,0,0]]])
# new_hiddens = torch.FloatTensor([[[0.1627, 0.4812, 0.1167, 0.4318],
#                                 [0.1627, 0.4812, 0.1167, 0.4318],
#                                 [0.6566, 0.2719, 0.7182, 0.1083]],

#                                 [[0.6642, 0.4301, 0.5542, 0.3670],
#                                 [0.9372, 0.4993, 0.5471, 0.9169],
#                                         [0.9372, 0.4993, 0.5471, 0.9169]]])
    # """


In [86]:
expanded_beam_id
expanded_beam_id = beam_id.unsqueeze(2).expand(-1, -1, hiddens.size(2))
expanded_beam_id

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0]],

        [[2, 2, 2, 2],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [88]:
new_hiddens = torch.gather(hiddens, 1, expanded_beam_id)
new_hiddens = torch.gather(hiddens, 1, expanded_beam_id)
new_hiddens

tensor([[[0.1627, 0.4812, 0.1167, 0.4318],
         [0.1627, 0.4812, 0.1167, 0.4318],
         [0.6566, 0.2719, 0.7182, 0.1083]],

        [[0.6642, 0.4301, 0.5542, 0.3670],
         [0.9372, 0.4993, 0.5471, 0.9169],
         [0.9372, 0.4993, 0.5471, 0.9169]]])

In [72]:
beam_id

tensor([[1, 1, 0],
        [2, 0, 0]])

In [16]:
beam_id= torch.LongTensor([[1, 1, 0], [2, 0, 0]])

In [19]:
batch_sz, beam_sz = beam_id.shape
new_hiddens = torch.zeros_like(hiddens)
for i in range(batch_sz):
    for j in range(beam_sz):
        new_hiddens[i][j] = hiddens[i][beam_id[i][j]]

In [20]:
new_hiddens

tensor([[[0.1627, 0.4812, 0.1167, 0.4318],
         [0.1627, 0.4812, 0.1167, 0.4318],
         [0.6566, 0.2719, 0.7182, 0.1083]],

        [[0.6642, 0.4301, 0.5542, 0.3670],
         [0.9372, 0.4993, 0.5471, 0.9169],
         [0.9372, 0.4993, 0.5471, 0.9169]]])

In [55]:
top_score = torch.Tensor([[ 0.00, -0.02, -0.03, -0.03, -0.04],
                              [ 0.00, -0.00, -0.03, -0.03, -0.03],
                              [ 0.00, -0.00, -0.11, -0.11, -0.13]])
top_wordids = [
    torch.LongTensor([[ 3, 12,  5,  4,  9], [12, 11,  9,  5,  8], [ 3,  8, 11,  4,  5]]), 
    torch.LongTensor([[12,  1,  0, 12, 12], [ 7,  7,  7,  4,  7], [ 4,  0,  2,  7,  4]]), 
    torch.LongTensor([[13,  2, 13, 13, 13], [ 8,  5,  8,  5,  8], [ 9,  9,  2,  2,  9]]), 
    torch.LongTensor([[ 8,  2,  8,  8,  8], [ 5,  5,  5,  5,  5], [11, 11,  1,  1,  9]]), 
    torch.LongTensor([[ 5,  2,  5,  5,  5], [10, 10, 10, 10, 10], [ 6,  6,  2,  2,  0]]), 
    torch.LongTensor([[6, 7, 2, 6, 6], [6, 6, 7, 6, 7], [1, 1, 2, 2, 1]]), 
    torch.LongTensor([[1, 1, 2, 1, 1], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2]])
]
top_beamids = [
    torch.LongTensor([[1, 4, 1, 1, 2], [0, 1, 0, 0, 0], [2, 3, 4, 4, 2]]), 
    torch.LongTensor([[0, 1, 0, 2, 3], [0, 2, 3, 0, 4], [0, 0, 1, 2, 4]]), 
    torch.LongTensor([[0, 1, 2, 3, 4], [0, 0, 1, 1, 2], [0, 1, 0, 1, 4]]), 
    torch.LongTensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 0, 1, 0]]), 
    torch.LongTensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 0]]),
    torch.LongTensor([[0, 0, 1, 2, 3], [0, 1, 0, 2, 1], [0, 1, 2, 3, 4]]), 
    torch.LongTensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
]
sequence = torch.LongTensor([[[ 3, 12, 13,  8,  5,  6,  1],
                            [ 3, 12, 13,  8,  5,  7,  1],
                            [12,  1,  2,  2,  2,  2,  2],
                            [ 3,  0, 13,  8,  5,  6,  1],
                            [ 5, 12, 13,  8,  5,  6,  1]],

                            [[12,  7,  8,  5, 10,  6,  1],
                            [12,  7,  5,  5, 10,  6,  1],
                            [12,  7,  8,  5, 10,  7,  1],
                            [ 9,  7,  8,  5, 10,  6,  1],
                            [12,  7,  5,  5, 10,  7,  1]],

                            [[ 3,  4,  9, 11,  6,  1,  2],
                            [ 3,  0,  9, 11,  6,  1,  2],
                            [ 3,  4,  9,  1,  2,  2,  2],
                            [ 3,  0,  9,  1,  2,  2,  2],
                            [ 3,  4,  9, 11,  0,  1,  2]]])
sort_score = torch.FloatTensor([[ 0.00, -0.02, -0.03, -0.03, -0.04],
                                [ 0.00, -0.00, -0.03, -0.03, -0.03],
                                [ 0.00, -0.00, -0.11, -0.11, -0.13]])

In [60]:
top_beamids[6][0][3]

tensor(3)

In [51]:
top_beamids[6][1][0]

tensor(0)

In [77]:

batch_size, beam_size =  top_score.shape
decode_max_length = len(top_wordids)
sequences = torch.LongTensor(batch_size, beam_size, decode_max_length)
print(batch_size, beam_size, decode_max_length)
batch =[]
for i in range(batch_size):
    beam = []
    for j in range(beam_size):
        seq = []
        beam_selected = j
        for k in range(decode_max_length-1, -1, -1):
            # print(i, j, k)
            sequences[i][j][k] = top_wordids[k][i][beam_selected]
            beam_selected = top_beamids[k][i][beam_selected]
                 
    


3 5 7


In [78]:
sequences

tensor([[[ 3, 12, 13,  8,  5,  6,  1],
         [ 3, 12, 13,  8,  5,  7,  1],
         [12,  1,  2,  2,  2,  2,  2],
         [ 3,  0, 13,  8,  5,  6,  1],
         [ 5, 12, 13,  8,  5,  6,  1]],

        [[12,  7,  8,  5, 10,  6,  1],
         [12,  7,  5,  5, 10,  6,  1],
         [12,  7,  8,  5, 10,  7,  1],
         [ 9,  7,  8,  5, 10,  6,  1],
         [12,  7,  5,  5, 10,  7,  1]],

        [[ 3,  4,  9, 11,  6,  1,  2],
         [ 3,  0,  9, 11,  6,  1,  2],
         [ 3,  4,  9,  1,  2,  2,  2],
         [ 3,  0,  9,  1,  2,  2,  2],
         [ 3,  4,  9, 11,  0,  1,  2]]])

In [72]:
sequence = torch.LongTensor([[[ 3, 12, 13,  8,  5,  6,  1],
                            [ 3, 12, 13,  8,  5,  7,  1],
                            [12,  1,  2,  2,  2,  2,  2],
                            [ 3,  0, 13,  8,  5,  6,  1],
                            [ 5, 12, 13,  8,  5,  6,  1]],

                            [[12,  7,  8,  5, 10,  6,  1],
                            [12,  7,  5,  5, 10,  6,  1],
                            [12,  7,  8,  5, 10,  7,  1],
                            [ 9,  7,  8,  5, 10,  6,  1],
                            [12,  7,  5,  5, 10,  7,  1]],

                            [[ 3,  4,  9, 11,  6,  1,  2],
                            [ 3,  0,  9, 11,  6,  1,  2],
                            [ 3,  4,  9,  1,  2,  2,  2],
                            [ 3,  0,  9,  1,  2,  2,  2],
                            [ 3,  4,  9, 11,  0,  1,  2]]])

IndexError: list index out of range

In [69]:
sequences = torch.LongTensor(batch_size, beam_size, decode_max_length)
sequences.shape

torch.Size([3, 5, 7])

In [24]:
k = torch.LongTensor([[1, 4, 1, 1, 2], [0, 1, 0, 0, 0], [2, 3, 4, 4, 2]])

In [29]:
k[:, 0]

tensor([1, 0, 2])